GET http://localhost:3001/

# NOTE: Get all the persons
GET http://localhost:3001/api/persons

# NOTE: Get one person
GET http://localhost:3001/api/persons/1

# GET Person non-existent
GET http://localhost:3001/api/persons/22002

# person POST without name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "12345"
}

# person POST
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Albert Einstein",
  "number": "777-888-999"
}

# GET info page
GET http://localhost:3001/info

# DELETE person
DELETE http://localhost:3001/api/persons/1

# DELETE attempt of non-existent person
DELETE http://localhost:3001/api/persons/99999
